service: lecshare-api

provider:
  name: aws
  region: us-west-2
  memorySize: 128
  runtime: go1.x

functions:
  playground:
    handler: bin/hello
    events:
      - http:
          path: /
          method: get
      - http:
          path: /
          method: post
  graphql:
    handler: bin/graph
    events:
      - http:
          path: /query
          method: get
      - http:
          path: /query
          method: post
package:
  exclude:
    - ./**
  include:
    - ./bin/**
plugins:
  - serverless-offline
