// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type Instructor struct {
	Title      *string `json:"title"`
	FirstName  string  `json:"firstName"`
	MiddleName *string `json:"middleName"`
	LastName   string  `json:"lastName"`
}

type NewClass struct {
	Term    string `json:"term"`
	Section string `json:"section"`
}

type NewCourse struct {
	Name        string  `json:"name"`
	Subject     string  `json:"subject"`
	Code        string  `json:"code"`
	Description string  `json:"description"`
	Homepage    *string `json:"homepage"`
}

type NewLecture struct {
	File        graphql.Upload `json:"file"`
	Date        time.Time      `json:"date"`
	Name        *string        `json:"name"`
	Description *string        `json:"description"`
}

type NewResource struct {
	File        *graphql.Upload `json:"file"`
	Date        *time.Time      `json:"date"`
	Name        *string         `json:"name"`
	Description *string         `json:"description"`
}

type Transcription struct {
	Transcripts []*string            `json:"transcripts"`
	Words       []*TranscriptionWord `json:"words"`
}

type TranscriptionWord struct {
	Type      string  `json:"type"`
	Starttime *string `json:"starttime"`
	Endtime   *string `json:"endtime"`
	Word      string  `json:"word"`
}

type UpdateResource struct {
	File        *graphql.Upload `json:"file"`
	Date        *time.Time      `json:"date"`
	Name        *string         `json:"name"`
	Description *string         `json:"description"`
	Published   *bool           `json:"published"`
}
