// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Class struct {
	Title      string     `json:"title"`
	Code       string     `json:"code"`
	Crn        string     `json:"crn"`
	Instructor *User      `json:"instructor"`
	Lectures   []*Lecture `json:"lectures"`
}

type Lecture struct {
	Name          string         `json:"name"`
	Datetime      string         `json:"datetime"`
	Audio         *string        `json:"audio"`
	Duration      int            `json:"duration"`
	Transcription *Transcription `json:"transcription"`
}

type Resource struct {
	ContentType *string `json:"contentType"`
	URL         *string `json:"url"`
}

type School struct {
	Name      string   `json:"name"`
	Shortname string   `json:"shortname"`
	Classes   []*Class `json:"classes"`
}

type Transcription struct {
	Sections []*TranscriptionSection `json:"sections"`
}

type TranscriptionParagraph struct {
	Transcript string               `json:"transcript"`
	Confidence float64              `json:"confidence"`
	Words      []*TranscriptionWord `json:"words"`
}

type TranscriptionSection struct {
	Alternatives []*TranscriptionParagraph `json:"alternatives"`
	LanguageCode string                    `json:"languageCode"`
}

type TranscriptionWord struct {
	Starttime  *WordTime `json:"starttime"`
	Endtime    *WordTime `json:"endtime"`
	Word       string    `json:"word"`
	Confidence float64   `json:"confidence"`
}

type User struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Prefix    string `json:"prefix"`
	Role      string `json:"role"`
}

type WordTime struct {
	Seconds *string `json:"seconds"`
	Nanos   *int    `json:"nanos"`
}

type Role string

const (
	RoleInstructor Role = "Instructor"
	RoleStudent    Role = "Student"
)

var AllRole = []Role{
	RoleInstructor,
	RoleStudent,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleInstructor, RoleStudent:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
