name: lecshare-api-deployment
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.8'
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Node Packages
      run: npm install
    - name: Run Makefile
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: make build
    - name: serverless deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: npm run deploy